#!/bin/bash
# This script demo how to decrypt the content of an aes-128-cbc b64 message if you know the key

# Decode b64 
cat enc | cut -c2- | tr -d “'” > enc.b64
base64 -di enc.b64 > enc.decode

# Optional, to remove noise headers and make the message multiple of 128 block (adapt) 
# xxd -p enc.decode | tr -d \\n | cut -c17- | xxd -r -p  > enc.decode2

# Extract IV (first 128 bits)
xxd -p enc.decode | tr -d \\n | cut -c1-32  > IV

# Extract encrypted Body
xxd -p enc.decode | tr -d \\n | cut -c33- | xxd -r -p > cipher

openssl enc -aes-128-cbc  -d -K $(cat KEY) -iv $(cat IV) -nopad -in cipher > message
